### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by rhdsu** [KJasonMontgomery/multiple-checkpoints#2]
Hello,

Wouldn't it be better to use "CreateDynamicCP" instead of the mapicon checkpoint (MAPICON_GLOBAL_CHECKPOINT)?

Using CreateDynamicCP, it would be possible to add two more parameters to the function "ShowCP", size, and stream distance from a checkpoint.

**Comment by ghost** [comment]
Hello,

I think you misunderstood what this library is supposed to do, it is supposed to show more than one checkpoint at the same time!
Streamer only stream the closest checkpoint to the player.

Best regards, Jason Montgomery.

**Comment by RHudBB** [comment]
Hello,

I understand that the library's main feature is to show all checkpoints.

So it would be nice if you could choose between 'ShowCP', and another one that could change the stream distance and size, but would not appear in every checkpoint, but only the mapicon.
